# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../chef-repo/cookbooks/hudl_work/Berksfile"
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "hudl_work"
    chef.cookbooks_path = "../chef-repo/cookbooks"
  end
#  config.vm.provision "docker" do |d|
#    d.pull_images "mongo:3.0"
#    d.run "mongo", 
#    	args: "-p '27017:27017'"
#  end
#  config.vm.network "forwarded_port", guest: 27017, host: 27017
   if VAGRANT_COMMAND == "ssh"
        config.ssh.username = 'chris'
    end
end
