name 'hudl_work'
maintainer 'Chris Lewis'
maintainer_email 'chris.lewis@hudl.com'
license 'all_rights'
description 'Installs/Configures hudl_work'
long_description 'Installs/Configures hudl_work'
version '0.1.0'
depends 'git', '~> 4.3'
