# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  
  config.vm.synced_folder "../../../../.ssh/", "/synced_ssh"
  
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../chef-repo/cookbooks/hudl_work/Berksfile"
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "hudl_work"
    chef.cookbooks_path = "../chef-repo/cookbooks"
  end
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'chris'
    config.ssh.private_key_path =  "../../../../.ssh/id_rsa"
  end
end